name: main
on: [push, pull_request]
strategy:
  matrix:
    os: [ubuntu-16.04, ubuntu-18.04]

jobs:
  firebase-deploy:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.19.0'
    - run: npm install
    - run: npm run publish